# Generated by Django 3.0.5 on 2020-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_plot', models.TextField()),
                ('book_pages_number', models.IntegerField()),
                ('book_release_date', models.DateField()),
                ('book_language', models.CharField(max_length=50)),
                ('book_image', models.CharField(max_length=500)),
            ],
        ),
    ]
