# Generated by Django 3.0.5 on 2020-05-09 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('dismission_date', models.DateField()),
                ('book_isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm.Book')),
            ],
        ),
    ]
