# Generated by Django 3.0.5 on 2020-05-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0002_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
