# Generated by Django 3.0.5 on 2020-05-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0008_auto_20200525_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_language',
        ),
        migrations.AddField(
            model_name='book',
            name='Language_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookworm.Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookworm.Country'),
        ),
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.ManyToManyField(to='bookworm.Editor'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm.Country'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editor',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm.Country'),
        ),
    ]
