# Generated by Django 3.0.5 on 2020-05-27 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0016_auto_20200527_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='editor',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='volume_id',
            new_name='volume',
        ),
        migrations.RenameField(
            model_name='volume',
            old_name='book_isbn',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm.Country'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm.Country'),
        ),
    ]
