# Generated by Django 3.0.5 on 2020-06-09 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0019_auto_20200609_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_user_info',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm.Country'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm.Country'),
        ),
    ]
