# Generated by Django 3.0.5 on 2020-06-10 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookworm', '0022_auto_20200610_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sezione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm.Country'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm.Country'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='borrow_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 10, 15, 14, 41, 457892)),
        ),
        migrations.AddField(
            model_name='book',
            name='sezione',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookworm.Sezione'),
        ),
    ]
